spring.datasource.url=jdbc:postgresql://a3usjt-projetoa3-45cb.i.aivencloud.com:15573/defaultdb?sslmode=require
spring.datasource.username=avnadmin
spring.datasource.password=AVNS_ACSo69Go05JmtbwAYch

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

spring.datasource.hikari.data-source-properties.ssl=true
spring.datasource.hikari.data-source-properties.sslmode=require
