spring.datasource.url=jdbc:h2:mem:infocheck;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
server.port=53842 

spring.jpa.hibernate.ddl-auto=update
spring.jpa.defer-datasource-initialization=true
spring.h2.console.enabled=true


newsapi.key=b26f33f557fd4527af02022c31ae45c5

spring.task.scheduling.enabled=true
